### ISSUE TITLE
JaxRsContextFilter throwing NullPointerException with TomEE

### ISSUE THREAD

**Issue by Daniel-Dos** [mvc-spec/ozark#131]
When doing a simple test with apache-tomee-plus-7.0.3 using the Ozark-core module, when running the application it accuses an NPE in the class JaxRsContextFilter.

I tried to make a separate module following the template that was made for RestEasy, added the following dependency in pom.xml: 

       
```
<dependency>
	<groupId>org.apache.cxf</groupId>
	<artifactId>cxf-rt-frontend-jaxrs</artifactId>
	<version>3.1.12</version>
	<scope>provided</scope>
</dependency>
```
but without success, it follows the log of the exception: 

```
exception

javax.servlet.ServletException: Error processing webservice request
    org.apache.tomee.webservices.CXFJAXRSFilter.doFilter(CXFJAXRSFilter.java:98)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:65)
root cause

java.lang.NullPointerException
    org.glassfish.ozark.jaxrs.JaxRsContextFilter.filter(JaxRsContextFilter.java:53)
    org.apache.cxf.jaxrs.utils.JAXRSUtils.runContainerRequestFilters(JAXRSUtils.java:1676)
    org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:106)
    org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:77)
    org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
    org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:262)
    org.apache.openejb.server.cxf.rs.CxfRsHttpListener.doInvoke(CxfRsHttpListener.java:253)
    org.apache.tomee.webservices.CXFJAXRSFilter.doFilter(CXFJAXRSFilter.java:94)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:65)
```

**Comment by chkal** [comment]
I don't think that we need a module for CXF now. We can add this as soon as we find anything we have to do to get Ozark to work correctly which requires CXF specific API..

Regarding the NPE: It looks like `@Inject` doesn't work on the JAX-RS filter. Not sure why this is happening. The JAX-RS 2.0 spec states:

> In a product that supports CDI, implementations MUST support the use of CDI-style Beans as root re-
source classes, providers and Application subclasses. Providers and Application subclasses MUST
be singletons or use application scope.

Therefore, IMO injection should work.

**Comment by chkal** [comment]
I think I found the reason why this is happening. See the corresponding upstream issue I just created:

https://issues.apache.org/jira/browse/TOMEE-2122

**Comment by Daniel-Dos** [comment]
I agree that you will not need a module for CXF and maybe not for the others, otherwise Ozark will be full of modules for the most diverse implementations of JAX-RS, so this may be damaging the compatibility.

Now the NPE is really strange because as the RestEasy module is working well with this JAX-RS filter and the other does not.

**Comment by Daniel-Dos** [comment]
HI @chkal 

Should we close this one for now?

**Comment by chkal** [comment]
Hmmm. Not sure. We could try to find out if the issue is caused by TomEE our by CXF. If it is a bug of CXF, we could try to open an issue in their JIRA project.

**Comment by Daniel-Dos** [comment]
In case you would be thinking of adding something like it was made for Jersey and RestEasy?

**Comment by chkal** [comment]
We should only add a `ozark-cxf` module if necessary. But the issue we ran into looks like a TomEE or CXF bug. And if it is a CXF bug, we should file an issue in their bug tracker so they can fix this. Not sure if the TomEE bug tracker is the correct place to report this.

**Comment by jeyvison** [comment]
@chkal , I can take a look at this.

**Comment by chkal** [comment]
That would be awesome! Thanks a lot.

**Comment by Daniel-Dos** [comment]
As no one answered the issue open by you, would be valid also opened the same for the CXF.

**Comment by chkal** [comment]
Maybe. But it would be even better if we could make sure that the problem is really with CXF itself and not with TomEE's integration layer.

**Comment by jeyvison** [comment]
Hey folks, just found out what is happening.  The Filter(*JaxRsContextFilter*) is instantiated and all fields should be injected when CXF JAXRSUtils is called to run all the container filters, but only the fields annotated with *@Context* are properly injected. Just opened an [issue](https://issues.apache.org/jira/browse/CXF-7501) to the CXF guys.

**Comment by chkal** [comment]
Awesome! Thanks a lot! I just added a reference to the TomEE issue I created before.

**Comment by jeyvison** [comment]
Well, now we wait then ^^

**Comment by chkal** [comment]
Hey all! I tried to implement the workaround mentioned in the CXF issue, but unfortunately Ozark stops to work with Jersey in this case. So I guess we have to wait until the issue is fixed in CXF. :disappointed:

**Comment by jeyvison** [comment]
Hey Folks. Just an update, the amazing CXF guys fixed the issue we opened to them and the fix is already available on two released versions: 3.2.1 and 3.1.14. I think we still need to wait the tomee folks to include these versions as dependency so we can test properly.

**Comment by chkal** [comment]
Thanks a lot. Perhaps someone could try to build an MVC sample app on top of Tomcat + RESTEasy to verify that everything works fine now? If this is the case, I very confident that it will also work in the next TomEE version which includes the new RESTEasy versions.

**Comment by Daniel-Dos** [comment]
temporary guide for the ozark run on tomcat / tomee.

https://github.com/mvc-spec/www.mvc-spec.org/pull/23

**Comment by chkal** [comment]
Awesome! Thanks a lot @Daniel-Dos.

BTW: Did anyone try to run the latest CXF version on Tomcat to verify that the recent CXF fixes the problems we ran into?

**Comment by Daniel-Dos** [comment]
Do not get the same headache, but I'll do it now.

**Comment by Daniel-Dos** [comment]
Hi,
I have tested with SNAPSHOT version doing a build of the TomEE github project.

But he introduced me yet. I just used Ozark-core .

when starting deploy, displays the following error:

```
dez 18, 2017 3:26:44 AM org.apache.openejb.observer.ObserverManager$MethodInvocation invoke
GRAVE: error invoking org.apache.tomee.webservices.TomeeJaxRsService@b62fe6d
org.apache.cxf.service.factory.ServiceConstructionException
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:219)
	at org.apache.openejb.server.cxf.rs.CxfRsHttpListener.deployApplication(CxfRsHttpListener.java:636)
	at org.apache.openejb.server.rest.RESTService.deployApplication(RESTService.java:481)
	at org.apache.openejb.server.rest.RESTService.afterApplicationCreated(RESTService.java:246)
	at org.apache.tomee.webservices.TomeeJaxRsService.afterApplicationCreated(TomeeJaxRsService.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.openejb.observer.ObserverManager$MethodInvocation.invoke(ObserverManager.java:406)
	at org.apache.openejb.observer.ObserverManager$InvocationList.invoke(ObserverManager.java:521)
	at org.apache.openejb.observer.ObserverManager.doFire(ObserverManager.java:111)
	at org.apache.openejb.observer.ObserverManager.fireEvent(ObserverManager.java:100)
	at org.apache.openejb.loader.SystemInstance.fireEvent(SystemInstance.java:134)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.afterStart(TomcatWebAppBuilder.java:1771)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:116)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:395)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.mvcspec.ozark.bootstrap.OzarkInitializer.isMvcApplication(OzarkInitializer.java:68)
	at org.mvcspec.ozark.bootstrap.OzarkInitializer.initialize(OzarkInitializer.java:50)
	at org.mvcspec.ozark.bootstrap.OzarkCoreFeature.configure(OzarkCoreFeature.java:41)
	at org.apache.cxf.jaxrs.provider.ServerProviderFactory.setProviders(ServerProviderFactory.java:206)
	at org.apache.cxf.jaxrs.provider.ProviderFactory.setUserProviders(ProviderFactory.java:791)
	at org.apache.cxf.jaxrs.AbstractJAXRSFactoryBean.setupFactory(AbstractJAXRSFactoryBean.java:332)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.setupFactory(JAXRSServerFactoryBean.java:237)
	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:182)
	... 24 more
```
after that and display the browser with the page and when I click to display a "Hello World" and displaying the following error 500:

```
dez 18, 2017 3:29:29 AM org.apache.catalina.core.StandardWrapperValve invoke
GRAVE: Servlet.service() for servlet [default] in context with path [/mvc] threw exception [Error processing webservice request] with root cause
java.lang.NullPointerException
	at org.apache.openejb.server.cxf.rs.CxfRsHttpListener.doInvoke(CxfRsHttpListener.java:253)
	at org.apache.tomee.webservices.CXFJAXRSFilter.doFilter(CXFJAXRSFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chkal** [comment]
Hi @Daniel-Dos,

thanks a lot for giving CXF another try. :-)

I just checked the code and it looks like the NPE is happening because `OzarkContainerInitializer` is called too later or not at all. I fixed the NPE in 9cd1f9c6c6375797068cf45bcfe5a7e8acffb5da but Ozark will most likely disable the providers, because the MVC application detection won't work. Perhaps you could try to debug whether or not `OzarkContainerInitializer` is executed!?!?

**Comment by chkal** [comment]
One additional note. I just committed d0186cfaefe50773b84164225a0d037f197894f6 which will enable Ozark even if controller detection doesn't work (because `OzarkContainerInitializer` isn't executed early enough). So maybe it just works now. But if `OzarkContainerInitializer` isn't executed at all, other failures may follow.

**Comment by dmaidaniuk** [comment]
@Daniel-Dos & @chkal,

I just made one more fix for NPE in `OzarkContainerInitializer`. This servlet initializer called successfully in TomEE but somehow `ServletContext` instance can't be injected in given initializer. See commit https://github.com/dmaidaniuk/ozark/commit/da2e63acea82177d9ea43a912d84baac8e60bf4a

However even with fix from [CXF-7501](https://issues.apache.org/jira/browse/CXF-7501) included in TomEE 7.0.5-SNAPSHOT, Ozark still not works properly and throws exception:
```
Caused by: java.lang.NullPointerException
        at org.mvcspec.ozark.jaxrs.JaxRsContextFilter.filter(JaxRsContextFilter.java:53)
        at org.apache.cxf.jaxrs.utils.JAXRSUtils.runContainerRequestFilters(JAXRSUtils.java:1692)
        at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:106)
        at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:77)
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        ... 31 more
```
I investigated a bit and see that possible source of problem could be that `DefaultConfigProvider` don't work with CXF. So our features configuration not happens. I will take a look further and will try to prepare some [integration module](http://cxf.apache.org/docs/features.html) for TomEE to see if it will solve this issue.

Regards,
Dmytro

**Comment by chkal** [comment]
Hmmm. Looks like `JaxRsContextProducer` isn't injected into `JaxRsContextFilter`. But actually CXF-7501 should fix that, no?

**Comment by chkal** [comment]
Hey all! Good news. I spent some time experimenting with Ozark and TomEE this morning and made some progress. Basic MVC applications seem to work fine now on the latest TomEE 7.0.5-SNAPSHOT. And I guess that the latest stable version also works, but I didn't test it yet.

So feel free to give it another try. :-)

Please refer to [this page](https://www.mvc-spec.org/ozark/docs/install-snapshots.html) to learn how to use the latest snapshots of Ozark.

The only problem I found so far is that binding and validation errors are not handled correctly. So this may need some more work. But if it is basically working, we should close this issue and create new issues for things that don't work correctly yet.

**Comment by Daniel-Dos** [comment]
it actually stopped giving this exception in both the 7.0.5 snapshot, the stable and the next version with Java EE 8 in the branch https://github.com/apache/tomee/tree/fb_tomee8 .

Even though I make a simple hello world, the same is not loading the page to show the result.

**Comment by chkal** [comment]
Hmmm. Are you using the latest snapshots? Could you include the exact stacktrace including line numbers?

**Comment by Daniel-Dos** [comment]
Hi, I'm using the last snapshot .

follows the Tomcat-7.0.5-SNAPSHOT log:



```
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
WARNING: [SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property 'source' to 'org.eclipse.jst.jee.server:tomee' did not find a matching property.
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: Server version:        Apache Tomcat (TomEE)/8.5.30 (7.0.5-SNAPSHOT)
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: Server built:          Apr 3 2018 20:04:09 UTC
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: Server number:         8.5.30.0
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: OS Name:               Linux
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: OS Version:            4.10.0-38-generic
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: Architecture:          amd64
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: JVM Version:           1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: JVM Vendor:            Oracle Corporation
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: CATALINA_BASE:         /home/eds00187/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp1
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: CATALINA_HOME:         /home/eds00187/Downloads/apache-tomee-webprofile-7.0.5-SNAPSHOT
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: Command line argument: -Dcatalina.base=/home/eds00187/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp1
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: Command line argument: -Dcatalina.home=/home/eds00187/Downloads/apache-tomee-webprofile-7.0.5-SNAPSHOT
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: Command line argument: -Dwtp.deploy=/home/eds00187/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: Command line argument: -Djava.endorsed.dirs=/home/eds00187/Downloads/apache-tomee-webprofile-7.0.5-SNAPSHOT/endorsed
May 17, 2018 4:01:37 PM sun.reflect.NativeMethodAccessorImpl invoke
INFO: Command line argument: -Dfile.encoding=UTF-8
May 17, 2018 4:01:37 PM sun.reflect.DelegatingMethodAccessorImpl invoke
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
May 17, 2018 4:01:37 PM sun.reflect.DelegatingMethodAccessorImpl invoke
INFO: Initializing ProtocolHandler ["http-nio-8080"]
May 17, 2018 4:01:37 PM sun.reflect.DelegatingMethodAccessorImpl invoke
INFO: Using a shared selector for servlet write/read
May 17, 2018 4:01:37 PM sun.reflect.DelegatingMethodAccessorImpl invoke
INFO: Initializing ProtocolHandler ["ajp-nio-8009"]
May 17, 2018 4:01:37 PM sun.reflect.DelegatingMethodAccessorImpl invoke
INFO: Using a shared selector for servlet write/read
May 17, 2018 4:01:37 PM org.apache.openejb.util.OptionsLog info
INFO: Using 'openejb.jdbc.datasource-creator=org.apache.tomee.jdbc.TomEEDataSourceCreator'
May 17, 2018 4:01:38 PM org.apache.openejb.OpenEJB$Instance <init>
INFO: ********************************************************************************
May 17, 2018 4:01:38 PM org.apache.openejb.OpenEJB$Instance <init>
INFO: OpenEJB http://tomee.apache.org/
May 17, 2018 4:01:38 PM org.apache.openejb.OpenEJB$Instance <init>
INFO: Startup: Thu May 17 16:01:38 BRT 2018
May 17, 2018 4:01:38 PM org.apache.openejb.OpenEJB$Instance <init>
INFO: Copyright 1999-2018 (C) Apache OpenEJB Project, All Rights Reserved.
May 17, 2018 4:01:38 PM org.apache.openejb.OpenEJB$Instance <init>
INFO: Version: 7.0.5-SNAPSHOT
May 17, 2018 4:01:38 PM org.apache.openejb.OpenEJB$Instance <init>
INFO: Build date: 20180517
May 17, 2018 4:01:38 PM org.apache.openejb.OpenEJB$Instance <init>
INFO: Build time: 01:05
May 17, 2018 4:01:38 PM org.apache.openejb.OpenEJB$Instance <init>
INFO: ********************************************************************************
May 17, 2018 4:01:38 PM org.apache.openejb.OpenEJB$Instance <init>
INFO: openejb.home = /home/eds00187/Downloads/apache-tomee-webprofile-7.0.5-SNAPSHOT
May 17, 2018 4:01:38 PM org.apache.openejb.OpenEJB$Instance <init>
INFO: openejb.base = /home/eds00187/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp1
May 17, 2018 4:01:38 PM org.apache.openejb.cdi.CdiBuilder initializeOWB
INFO: Created new singletonService org.apache.openejb.cdi.ThreadSingletonServiceImpl@1a38c59b
May 17, 2018 4:01:38 PM org.apache.openejb.cdi.CdiBuilder initializeOWB
INFO: Succeeded in installing singleton service
May 17, 2018 4:01:38 PM org.apache.openejb.config.ConfigurationFactory init
INFO: TomEE configuration file is '/home/eds00187/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/conf/openejb.xml'
May 17, 2018 4:01:38 PM org.apache.openejb.config.ConfigurationFactory configureService
INFO: Configuring Service(id=Tomcat Security Service, type=SecurityService, provider-id=Tomcat Security Service)
May 17, 2018 4:01:38 PM org.apache.openejb.config.ConfigurationFactory configureService
INFO: Configuring Service(id=Default Transaction Manager, type=TransactionManager, provider-id=Default Transaction Manager)
May 17, 2018 4:01:38 PM org.apache.openejb.config.ConfigurationFactory configureService
INFO: Configuring Service(id=My DataSource, type=Resource, provider-id=Default JDBC Database)
May 17, 2018 4:01:38 PM org.apache.openejb.config.ConfigurationFactory configureService
INFO: Configuring Service(id=My Unmanaged DataSource, type=Resource, provider-id=Default JDBC Database)
May 17, 2018 4:01:38 PM org.apache.openejb.config.ConfigurationFactory configureService
INFO: Configuring Service(id=My Singleton Container, type=Container, provider-id=Default Singleton Container)
May 17, 2018 4:01:38 PM org.apache.openejb.config.ConfigurationFactory configureService
INFO: Configuring Service(id=My Stateful Container, type=Container, provider-id=Default Stateful Container)
May 17, 2018 4:01:38 PM org.apache.openejb.config.ConfigurationFactory configureService
INFO: Configuring Service(id=My Stateless Container, type=Container, provider-id=Default Stateless Container)
May 17, 2018 4:01:38 PM org.apache.openejb.config.DeploymentsResolver loadFrom
WARNING: File error: <Deployments dir="apps/"> - Does not exist: /home/eds00187/work/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/apps
May 17, 2018 4:01:38 PM org.apache.openejb.util.OptionsLog info
INFO: Using 'openejb.deployments.classpath=false'
May 17, 2018 4:01:38 PM org.apache.openejb.assembler.classic.Assembler createRecipe
INFO: Creating TransactionManager(id=Default Transaction Manager)
May 17, 2018 4:01:38 PM org.apache.openejb.assembler.classic.Assembler createRecipe
INFO: Creating SecurityService(id=Tomcat Security Service)
May 17, 2018 4:01:38 PM org.apache.openejb.assembler.classic.Assembler createRecipe
INFO: Creating Resource(id=My DataSource)
May 17, 2018 4:01:42 PM org.mvcspec.ozark.bootstrap.OzarkCoreFeature configure
WARNING: The ServletContext wasn't injected into the JAX-RS Feature class

```


and a link for project of test - >

 https://github.com/Daniel-Dos/TomCat-TomEE-MVC/tree/master/tomee-new

**Comment by chkal** [comment]
The version looks fine. The warning in the last row is expected too and no real problem. Are you getting an exception or does it simply not work? The log doesn't include an exception.

**Comment by Daniel-Dos** [comment]
I do not get any exceptions, just get on it and the screen with the link to call the view of the result.

**Comment by chkal** [comment]
Thanks. I will have a look at your sample app tomorrow.

**Comment by Daniel-Dos** [comment]
thanks .

**Comment by chkal** [comment]
@Daniel-Dos I just had a quick look at your app. I guess I found the problem:

It looks like controllers with a `void` return type don't work. Even if they are annotated with `@View`. CXF is always returning 204 "No Content" status code in this case. So if you return the view name from the controller as a string, it works fine.

Feel free to create an issue to track this incompatibility. Although I guess that this needs some adjustments on the CXF side.

**Comment by chkal** [comment]
Good news. No need to file an issue. `void` is now working correctly. See d5d17b6 for details.

**Comment by Daniel-Dos** [comment]
@chkal ,

incredible .

I tested it here with versions 7.0.4, 7.0.5 and with Java EE 8 everything is ok.

I'll close this issue.

thank you so much .

**Comment by chkal** [comment]
Awesome! Thanks for confirming!

I also added a new profile to our CI build which executes the TCK against TomEE. The build is currently failing because 4 of ~44 tests are failing. But that's a good start I think. ;-)

**Comment by Daniel-Dos** [comment]
It's certainly a good start.
