### ISSUE TITLE
Check why asciidoc sample app doesn't work on Glassfish 5.0

### ISSUE THREAD

**Issue by chkal** [mvc-spec/ozark#134]
I recently remove the asciidoc integration test from the build, because the sample app doesn't deploy to Glassfish 5.0 b25 any more. Back when we were using b09 everything was fine.

See the corresponding commit here: https://github.com/mvc-spec/ozark/commit/4a4b9b06d73e03553079693cf2bf52b289f29f55

It would be great if we could activate this test again. Any help on this is welcome.

**Comment by dmaidaniuk** [comment]
Hi @chkal,

I will take a look to this bug and provide my research results/pull-request for it in next few days.

Regards,
Dmytro

**Comment by chkal** [comment]
Thanks a lot! Looking forward to your analysis.

**Comment by Daniel-Dos** [comment]
Hi @chkal ,

When doing a test with the same, it seemed N errors, even updating for the last JAR of the asciidoc did not advance.
Browsing the net I found this issue: https://github.com/javaee/glassfish/issues/22224
the log report is similar to the problem that appeared for me testing the latest glassfish build.

**Comment by dmaidaniuk** [comment]
Hi @Daniel-Dos,

Actually our error has other source:

> [2017-09-06T23:18:37.358+0300] [glassfish 5.0] [SEVERE] [NCLS-CORE-00026] [javax.enterprise.system.core] [tid: _ThreadID=134 _ThreadName=admin-listener(6)] [timeMillis: 1504729117358] [levelValue: 1000] [[
  Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:Error instantiating :org.hibernate.validator.cdi.internal.ValidationExtension
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:239)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:328)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:496)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:540)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:536)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:535)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:566)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:558)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:557)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1465)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:110)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1847)
	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1723)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:254)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:232)
	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:276)
	at org.glassfish.admin.rest.resources.TemplateListOfResource.createResource(TemplateListOfResource.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
	at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:316)
	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:179)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:463)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:168)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:242)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ServiceConfigurationError: Error instantiating :org.hibernate.validator.cdi.internal.ValidationExtension
	at org.jboss.weld.util.ServiceLoader.createInstance(ServiceLoader.java:315)
	at org.jboss.weld.util.ServiceLoader.prepareInstance(ServiceLoader.java:247)
	at org.jboss.weld.util.ServiceLoader.loadService(ServiceLoader.java:215)
	at org.jboss.weld.util.ServiceLoader.loadServiceFile(ServiceLoader.java:185)
	at org.jboss.weld.util.ServiceLoader.reload(ServiceLoader.java:165)
	at org.jboss.weld.util.ServiceLoader.iterator(ServiceLoader.java:289)
	at org.glassfish.weld.DeploymentImpl.getExtensions(DeploymentImpl.java:466)
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:223)
	... 66 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.weld.util.ServiceLoader.createInstance(ServiceLoader.java:313)
	... 73 more
Caused by: java.lang.TypeNotPresentException: Type org.joda.time.ReadableInstant not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:90)
	at java.lang.Class.getGenericSuperclass(Class.java:777)
	at org.hibernate.validator.internal.util.TypeHelper.resolveTypeForClassAndHierarchy(TypeHelper.java:386)
	at org.hibernate.validator.internal.util.TypeHelper.resolveTypes(TypeHelper.java:351)
	at org.hibernate.validator.internal.util.TypeHelper.extractType(TypeHelper.java:327)
	at org.hibernate.validator.internal.engine.constraintvalidation.ClassBasedValidatorDescriptor.<init>(ClassBasedValidatorDescriptor.java:39)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintValidatorDescriptor.forClass(ConstraintValidatorDescriptor.java:49)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.putConstraints(ConstraintHelper.java:686)
	at org.hibernate.validator.internal.metadata.core.ConstraintHelper.<init>(ConstraintHelper.java:386)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:155)
	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:322)
	at org.hibernate.validator.cdi.internal.ValidationExtension.<init>(ValidationExtension.java:116)
	... 78 more
Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadableInstant
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.felix.framework.BundleWiringImpl.doImplicitBootDelegation(BundleWiringImpl.java:1738)
	at org.apache.felix.framework.BundleWiringImpl.searchDynamicImports(BundleWiringImpl.java:1675)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1511)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 103 more
]]


So main reason is absence of JodaTime library, which is [optional](https://mvnrepository.com/artifact/org.hibernate/hibernate-validator/5.4.1.Final) for Hibernate Validator. I will investigate why this optional dependency activated for ASCIIDoc test. However it could be similar issue with dependencies reorganization inside GF 5 modules as from referenced bug-report.

**Comment by chkal** [comment]
@dmaidaniuk + @Daniel-Dos 

Thanks a lot for investigating! I also think that this may be a Glassfish issue. Perhaps we could create a minimal reproducer and create a new GF issue? I'm also very surprised that this only happens with the asciidoc test. This one include jruby. Perhaps this is somehow related?

**Comment by dmaidaniuk** [comment]
@chkal,

I will prepare minimal reproducer today and report this bug to GF issue-tracker if it will reproduced without Ozark libs.
For sure issue goes from ASCIIDoc dependencies, either ASCIIDoc itself or jruby.

**Comment by dmaidaniuk** [comment]
Hi @chkal and @Daniel-Dos,

I just found that `jruby-complete` library really [contains inside classes](https://github.com/asciidoctor/asciidoctorj/issues/158) from JodaTime 2.5. I assume that latest GF 5 modules also used JodaTime library for own purposes. So it seems we have conflicted classes which classloader can't handle.
I tried replace `jruby-complete` with `jrube-core` and exclude JodaTime from transitive dependencies. After that testing application build and deployed successfully to GF 5 but when you try to open Controller path in browser next exception thrown:

> [2017-09-07T22:55:02.093+0300] [glassfish 5.0] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=31 _ThreadName=http-listener-1(2)] [timeMillis: 1504814102093] [levelValue: 900] [[
  StandardWrapperValve[org.mvcspec.ozark.test.asciidoc.MyApplication]: Servlet.service() for servlet org.mvcspec.ozark.test.asciidoc.MyApplication threw exception
java.lang.ClassNotFoundException: org.joda.time.IllegalFieldValueException
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1621)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1471)
	at org.jruby.Ruby.initCore(Ruby.java:1557)
	at org.jruby.Ruby.bootstrap(Ruby.java:1313)
	at org.jruby.Ruby.init(Ruby.java:1224)
	at org.jruby.Ruby.newInstance(Ruby.java:334)
	at org.jruby.javasupport.JavaEmbedUtils.initialize(JavaEmbedUtils.java:94)
	at org.asciidoctor.internal.JRubyAsciidoctor.createJRubyAsciidoctorInstance(JRubyAsciidoctor.java:126)
	at org.asciidoctor.internal.JRubyAsciidoctor.create(JRubyAsciidoctor.java:57)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:668)
	at org.mvcspec.ozark.ext.asciidoc.AsciiDocViewEngine.<init>(AsciiDocViewEngine.java:49)
	at org.mvcspec.ozark.ext.asciidoc.AsciiDocViewEngine$Proxy$_$$_WeldClientProxy.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jboss.weld.bean.proxy.DefaultProxyInstantiator.newInstance(DefaultProxyInstantiator.java:43)
	at org.jboss.weld.bean.proxy.ProxyFactory.run(ProxyFactory.java:344)
	at org.jboss.weld.bean.proxy.ProxyFactory.create(ProxyFactory.java:336)
	at org.jboss.weld.bean.proxy.ClientProxyFactory.create(ClientProxyFactory.java:83)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:205)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:195)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.access$100(ClientProxyProvider.java:44)
	at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.apply(ClientProxyProvider.java:52)
	at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.apply(ClientProxyProvider.java:48)
	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.lambda$null$0(ReentrantMapBackedComputingCache.java:55)
	at org.jboss.weld.util.LazyValueHolder$1.computeValue(LazyValueHolder.java:32)
	at org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:46)
	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:72)
	at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:78)
	at org.jboss.weld.bean.proxy.ClientProxyProvider.getClientProxy(ClientProxyProvider.java:229)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:670)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:699)
	at org.jboss.weld.util.ForwardingBeanManager.getReference(ForwardingBeanManager.java:64)
	at org.jboss.weld.bean.builtin.BeanManagerProxy.getReference(BeanManagerProxy.java:86)
	at org.mvcspec.ozark.util.CdiUtils.lambda$getApplicationBeans$0(CdiUtils.java:91)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.mvcspec.ozark.util.CdiUtils.getApplicationBeans(CdiUtils.java:92)
	at org.mvcspec.ozark.engine.ViewEngineFinder.find(ViewEngineFinder.java:79)
	at org.mvcspec.ozark.engine.ViewEngineFinder$Proxy$_$$_WeldClientProxy.find(Unknown Source)
	at org.mvcspec.ozark.core.ViewableWriter.writeTo(ViewableWriter.java:133)
	at org.mvcspec.ozark.core.ViewableWriter.writeTo(ViewableWriter.java:78)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:280)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1580)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:258)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:652)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:591)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:463)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:168)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:242)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:745)
]]

**Comment by Daniel-Dos** [comment]
Hi @dmaidaniuk and @chkal ,

At least we are aware that the problem is not with Ozark. I also tested it with a 1.6.0-alpha version.5. Now the doubt is would be a really problem with the glassfish or with the lib ?

**Comment by chkal** [comment]
Thank you very much for digging into this. Does this mean that the error always occurs if you deploy an application to Glassfish which contains Joda Time in `/WEB-INF/lib` (shaded or not)? If so, it should be easy to create an simple sample application which reproduces this and to report this to the Glassfish team.

**Comment by dmaidaniuk** [comment]
@chkal,
My assumption is yes, it always will be an issue when JodaTime will be present in `/WEB-INF/lib` application folder. But I need to verify it first. Even worse, if developer exclude it from his WAR, than still issue with `ClassNotFoundException` will be present because of JodaTime module visibility settings. At least that's what stack-trace above demonstrate.
I will prepare reproducer with ASCIIDoc lib first and than will try to go down to JodaTime lib only in WAR.

**Comment by dmaidaniuk** [comment]
Hi @chkal and @Daniel-Dos,

Unfortunately it is an issue with latest GF 5 b25 and JodaTime library usage. I just reported an issue javaee/glassfish#22270 with reproducer project. Let's wait for answer from GF developers.

**Comment by chkal** [comment]
Awesome! Thanks a lot for reproducing and reporting the issue. :beers:

**Comment by Daniel-Dos** [comment]
Very good, thanks for the info. Now it's waiting. : )

**Comment by dmaidaniuk** [comment]
I just checked reproducer with official release build of GlassFish 5 and issue is still there.

**Comment by chkal** [comment]
Thanks for checking this again. The upstream issue is also still open. I'm hoping that this will be fixed soon.

**Comment by chkal** [comment]
Good news. Looks like  the Glassfish issue will be fixed in 6.0.3.Final.

See all the details here: https://github.com/javaee/glassfish/issues/22270#issuecomment-335115598

**Comment by dmaidaniuk** [comment]
Hi @chkal,

Yes, I also received an update about this important for us bugfix.

**Comment by dmaidaniuk** [comment]
Hi,

It seems, reported issue is still not fixed. See next PR https://github.com/javaee/glassfish/pull/22315

Regards,
Dmytro

**Comment by Daniel-Dos** [comment]
Hello everyone,
I did the test with the latest version of glassfish 5.0.1 and did not give a problem to that one.

http://download.oracle.com/glassfish/5.0.1/nightly/latest-web.zip

**Comment by dmaidaniuk** [comment]
Hi @Daniel-Dos,

OK, I will uncomment required lines, test build and push changes today.

Thanks,
Dmytro

**Comment by chkal** [comment]
You can simply enable the module, update the Travis config and create the pull required. Travis will do the testing. ;)

**Comment by dmaidaniuk** [comment]
@chkal, yes, indeed. :)

**Comment by dmaidaniuk** [comment]
Issue seems fixed now for GlassFish 5.0.1 latest nightly build. PR passed on Travis.

**Comment by chkal** [comment]
Thanks a lot! Merged!

**Comment by chkal** [comment]
I guess we can close this one now. Thanks a lot for your help @Daniel-Dos and @dmaidaniuk!
