### ISSUE TITLE
Check if controllers are CDI beans

### ISSUE THREAD

**Issue by chkal** [mvc-spec/ozark#161]
The spec states:

> Unlike in JAX-RS [...], MVC classes are REQUIRED to be CDI-managed beans only"

Ozark should check that and fail if a controller is NOT a CDI beans. This could happen for example if the application is an implicit CDI archive in `annotated` discovery mode and the controller hasn't been defined with `@RequestScoped` or other scope annotations.

**Comment by mscharhag** [comment]
Do you have an idea on how to get the CDI discovery mode at runtime? I don't think CDI provides an easy way to get this information.

**Comment by chkal** [comment]
Not sure if this is possible at all using the standard CDI API.

However, I don't think that this is necessary to fix this issue. Basically we could just check whether the controller is a CDI bean in a `ContainerRequestFilter` which has access to the resource class. We could even use `ViewRequestFilter` for this. In this case we could simply ask the `BeanManager` for the corresponding class, which should always give us a result if the controller is a CDI bean. If the `BeanManager` doesn't know about the resource class, it won't be a CDI bean.

Does this make sense?

**Comment by mscharhag** [comment]
Yes, you are right. Checking the BeanManager should be enough.

I am trying to look into this. However, I'm a bit confused.

I created a sample application with `annotated` discovery mode and a controller class without any scope annotation. If I run this application with glassfish/jersey an exception is thrown before `ViewRequestFilter` is processed. So checking it there would be too late.

```
org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=Models,parent=TestController,qualifiers={},position=-1,optional=false,self=false,unqualified=null,1007007569)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:75)
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:1012)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:1008)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.inject(AbstractHk2InjectionManager.java:231)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.inject(ImmediateHk2InjectionManager.java:54)
	at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanSupplier$2.getInstance(AbstractCdiBeanSupplier.java:112)
	at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanSupplier._provide(AbstractCdiBeanSupplier.java:127)
	at org.glassfish.jersey.ext.cdi1x.internal.GenericCdiBeanSupplier.get(GenericCdiBeanSupplier.java:66)
	at org.glassfish.jersey.inject.hk2.InstanceSupplierFactoryBridge.provide(InstanceSupplierFactoryBridge.java:77)
	at org.jvnet.hk2.internal.FactoryCreator.create(FactoryCreator.java:153)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:710)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:184)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:54)
	at org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:129)
	at org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:284)
	at org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:75)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:110)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:93)
	at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:62)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1622)
	...
```
(Models cannot be injected in my controller)

If I run the application with Wildfly/Resteasy no Exception is thrown. 
Calling
```
Set<Bean<?>> cdiBeans = CdiUtils.getApplicationBeanManager().getBeans(resourceInfo.getResourceClass());
```
in `ViewRequestFilter` returns the Controller class. So the controller seems to be a managed CDI bean even it does not have a scope annotation. So it does not seem to be a problem with Wildfly/Resteasy (?)

**Comment by chkal** [comment]
Awesome! Thanks a lot for sharing these details.

To be honest, I don't remember anymore which exception I got when running into this issue while working on the TCK. But it may have been the exception you included above.

One question: In the Wildfly case, did injecting `Models` work as expected? If yes, there isn't any problem with Wildfly at all. It is possible, that RESTEasy converts all JAX-RS resources into CDI beans. In this case you will never run into any problems, even with discovery mode `annotated`.

Regarding Glassfish: It is too bad that the error is thrown before we get a chance to check it our self. However, the exception thrown is a bit cryptic and I guess that people won't immediately know what the root cause is.

One other way to improve the situation would be to check if all controllers are CDI beans in the bootstrap phase, so we can "fail early". Something like this:

1. Ozark is already collecting a [list of all controller classes](https://github.com/mvc-spec/ozark/blob/8a5ed55d9ff1341bae9b05832361918ea4f96678/core/src/main/java/org/mvcspec/ozark/servlet/OzarkContainerInitializer.java#L66) using a `ServletContainerInitializer`. There is already [one case](https://github.com/mvc-spec/ozark/blob/8a5ed55d9ff1341bae9b05832361918ea4f96678/core/src/main/java/org/mvcspec/ozark/uri/UriTemplateParser.java#L64-L65) for which we use this class list.
2. Ozark could then use the [CDI extension](https://github.com/mvc-spec/ozark/blob/8a5ed55d9ff1341bae9b05832361918ea4f96678/core/src/main/java/org/mvcspec/ozark/cdi/OzarkCdiExtension.java) to observe `AfterBeanDiscovery` and then check all the controller classes by asking the `BeanManager` if the class is a CDI managed bean.

Just a quick thought. Not sure if it is a good idea and whether it works. ;-)

Thoughts?

**Comment by mscharhag** [comment]
Thanks for your feedback

> One question: In the Wildfly case, did injecting Models work as expected? If yes, there isn't any problem with Wildfly at all. It is possible, that RESTEasy converts all JAX-RS resources into CDI beans.

I am pretty sure it worked. I will validate this again. By using the debugger I also saw a `@RequestScope` annotation on the controller `Bean` instance returned by the `BeanManager`. This annotation wasn't provided by me. I think it is added via [ResteasyCdiExtension](https://github.com/resteasy/Resteasy/blob/master/resteasy-cdi/src/main/java/org/jboss/resteasy/cdi/ResteasyCdiExtension.java)
 
I'll try to check controllers during startup when I am back from vacation.

**Comment by chkal** [comment]
Great! Thanks a lot! Looking forward to your reply. Enjoy your vacation.

**Comment by chkal** [comment]
I just want to point everyone to #177 which *could* also be fixed as part of this issue!?!?

**Comment by mscharhag** [comment]
I checked Wildfly again. The injected Models instance worked as expected. 

Using the BeanManager.getBeans(..) confirms this behaviour:
- When using Wildfly I get a controller bean from the BeanManager
- When using Glassfish I get an empty collection from the BeanManager

However, it looks like the AfterBeanDiscovery event is triggered before OzarkContainerInitializer is called. So maybe we should add this check to OzarkContainerInitializer?

**Comment by chkal** [comment]
Hmmm. Good question. I'm not sure if we can assume that CDI initializes before `OzarkContainerInitializer`  gets called in all containers. To be honest, my guess is that it is the other way around if you deploy the CDI implementation as part of the WAR to a container like Tomcat. But I'm not sure about that.

Maybe we could use a `ServletContextListener` instead? AFAIK this one gets notified after the initialization is complete, which means that both CDI is initialized and `OzarkContainerInitializer` was executed. So when such a listener is executed, everything you need should be available.

What do you think?

**Comment by mscharhag** [comment]
I tested the `ServletContextListener` variant and it seems to work fine. I'll try to implement this and create a pull request, so you can have a look.

Just a few more questions:

Do you have a preferred name for the exception that should be thrown? `ControllerNotManagedByCdiException`, `ControllerMissingScopeAnnotationException`, ... ?

Can you give me some hints regarding tests?
Writing a unit test should be easy. However, I think this type of feature should be tested on different containers using an integration test.
I noticed the `ozark-parent-test` module. Should I add a new sub module to test this behaviour? Is it even possible to test exceptions during container startup?

**Comment by chkal** [comment]
> I tested the ServletContextListener variant and it seems to work fine. I'll try to implement this and create a pull request, so you can have a look.

Awesome! :+1: 

> Do you have a preferred name for the exception that should be thrown? ControllerNotManagedByCdiException, ControllerMissingScopeAnnotationException, ... ?

I would be fine with simply throwing an `java.lang.IllegalStateException` with an appropriate text. I don't think that we need any special exception type for that. Especially because this exception happens during bootstrap and cannot really be handled in any way by the developer. 

> Do you know an case in which the BeanManager might return more than one Bean<?> instance for a given controller class?

I don't think that this happens in real world applications. But technically it is possible. One could create a producer that produces different instances of the same class using different qualifiers. But this would be a weird setup.

> Can you give me some hints regarding tests?
> Writing a unit test should be easy. However, I think this type of feature should be tested on different containers using an integration test.
> I noticed the ozark-parent-test module. Should I add a new sub module to test this behaviour? Is it even possible to test exceptions during container startup?

Good question. I don't know if it is possible to verify failed deployments. The current integration tests basically just deploy WAR files to a running container and then send HTTP requests to verify the expected behavior. I guess that verifying failed deployments won't be possible this way.

However, I think the most important aspect of this feature is that it doesn't break valid deployments. And this is actually already covered by all existing tests. :laughing: 

The error thrown for non-CDI controllers should actually be just a hint for the developer what the problem is instead of throwing some weird NPEs afterwards. So I would actually be fine with not having test coverage for this case. Of course unit tests would be great if you see code that can be easily tested.

> I think the same listener / loop can be used to check for the @Named annotation (#177)

I was hoping that we can also fix #177 with this. :smile: 

PS: Thanks a lot for your help with this.
